services:
  test:
    build:
      context: ./
      dockerfile: Dockerfile.ci
    env_file:
      - .env
    environment:
      - INTENT_LLM_MATCHING=true
      - INTENT_CHAR_MATCHING=true
      - TEST_MODE=true
    command: ["./run_tests.sh", "${TEST_FILES:-}"]

  test-int:
    build:
      context: ./
      dockerfile: Dockerfile.ci
    env_file:
     - .env
    environment:
      - INTENT_LLM_MATCHING=true
      - INTENT_CHAR_MATCHING=true
      - RUN_INTEGRATION_TESTS=1
      - TEST_MODE=true
    command: ["./run_tests.sh", "${TEST_FILES:-}"]

  ## For shell access and involve tooling, code are mounted
  shell:
    build:
      context: ./
      dockerfile: Dockerfile.ci
    env_file:
     - .env
    volumes:
      - './fluctlight:/app/home/fluctlight'
      - './tests:/app/home/tests'
    command: /bin/bash -c "while true; do sleep 3600; done"
